# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 23:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slot_machine', '0002_auto_20151215_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderedPoem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.BinaryField()),
                ('type', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='poem',
            name='handwriting_id',
            field=models.CharField(default='2D5QW0F80001', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='word',
            name='text',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Enter one word without spaces or punctuation.', regex='^[\\-a-zA-Z\xc0-\u017f]{1,255}$')]),
        ),
        migrations.AddField(
            model_name='renderedpoem',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot_machine.Poem'),
        ),
    ]
